#!/bin/bash

if (($#==0))
then 
    FILENAME=""
else
    FILENAME=$(basename $1)
fi
X=${#FILENAME}
((X--))
for Y in $(seq 0 $X)
do
    if [[ ${FILENAME:$Y:1} = . ]]
    then
	echo ${FILENAME:$Y}
    fi
done
